## 语言模型  
给定一个长度为T的序列$w_1, w_2, ... w_t$，语言模型计算该序列的概率$P(w_1, w_2, ..., w_t)$。   
例子：


In [1]:
import torch

In [6]:
x, w_xh = torch.randn(3, 1), torch.randn(1, 4)
h, w_hh = torch.randn(3, 4), torch.randn(4, 4)

In [7]:
torch.matmul(x, w_xh) + torch.matmul(h, w_hh)

tensor([[ 0.1889,  2.1129, -1.0467,  0.7654],
        [-0.6608, -3.3971, -0.0475,  0.6381],
        [ 0.1069, -1.1286,  0.7922,  0.7147]])

In [10]:
torch.cat((x, h), dim=1)

tensor([[ 0.1015, -0.3397, -1.3168,  0.5303,  0.3598],
        [-0.7769, -0.6548, -0.0791, -1.6986, -0.2289],
        [-0.7696,  0.3902,  1.2559,  0.5341, -0.1995]])

In [11]:
torch.cat((w_xh, w_hh))

tensor([[ 0.0967,  1.0799,  0.6121, -1.4363],
        [ 0.0170, -0.0126, -1.5922, -0.5048],
        [ 0.0250, -0.8821,  1.3357, -0.3460],
        [ 0.3188,  1.5451,  0.3230,  0.4812],
        [ 0.1352,  0.0504, -0.1730,  0.0804]])

In [12]:
torch.matmul(torch.cat((x, h), dim=1), torch.cat((w_xh, w_hh)))

tensor([[ 0.1889,  2.1129, -1.0467,  0.7654],
        [-0.6608, -3.3971, -0.0475,  0.6381],
        [ 0.1069, -1.1286,  0.7922,  0.7147]])

In [13]:
import zipfile

In [ ]:
with zipfile.ZipFile('./dara/jaychou_lyrics.txt.zip') as zin:
    with zin.open('jaychou_lyrics.txt') as f:
        lyrics = f.read().decode('utf-8')