## 语言模型  
给定一个长度为T的序列$w_1, w_2, ... w_t$，语言模型计算该序列的概率$P(w_1, w_2, ..., w_t)$。   
例子：


In [1]:
import torch

In [6]:
x, w_xh = torch.randn(3, 1), torch.randn(1, 4)
h, w_hh = torch.randn(3, 4), torch.randn(4, 4)

In [7]:
torch.matmul(x, w_xh) + torch.matmul(h, w_hh)

tensor([[ 0.1889,  2.1129, -1.0467,  0.7654],
        [-0.6608, -3.3971, -0.0475,  0.6381],
        [ 0.1069, -1.1286,  0.7922,  0.7147]])

In [10]:
torch.cat((x, h), dim=1)

tensor([[ 0.1015, -0.3397, -1.3168,  0.5303,  0.3598],
        [-0.7769, -0.6548, -0.0791, -1.6986, -0.2289],
        [-0.7696,  0.3902,  1.2559,  0.5341, -0.1995]])

In [11]:
torch.cat((w_xh, w_hh))

tensor([[ 0.0967,  1.0799,  0.6121, -1.4363],
        [ 0.0170, -0.0126, -1.5922, -0.5048],
        [ 0.0250, -0.8821,  1.3357, -0.3460],
        [ 0.3188,  1.5451,  0.3230,  0.4812],
        [ 0.1352,  0.0504, -0.1730,  0.0804]])

In [12]:
torch.matmul(torch.cat((x, h), dim=1), torch.cat((w_xh, w_hh)))

tensor([[ 0.1889,  2.1129, -1.0467,  0.7654],
        [-0.6608, -3.3971, -0.0475,  0.6381],
        [ 0.1069, -1.1286,  0.7922,  0.7147]])

In [13]:
import zipfile

In [20]:
with zipfile.ZipFile('../data/jaychou_lyrics.txt.zip') as zin:
    with zin.open('jaychou_lyrics.txt') as f:
        lyrics = f.read().decode('utf-8')
lyrics[:50]

'想要有直升机\n想要和你飞到宇宙去\n想要和你融化在一起\n融化在宇宙里\n我每天每天每天在想想想想著你\n这'

In [21]:
lyrics = lyrics.replace('\n', ' ').replace('\r', ' ')
lyrics = lyrics[:10000]

In [22]:
lyrics[:50]

'想要有直升机 想要和你飞到宇宙去 想要和你融化在一起 融化在宇宙里 我每天每天每天在想想想想著你 这'

In [23]:
idx_to_char = list(set(lyrics))

In [25]:
idx_to_char[:10]

['丘', '拥', '唱', '更', '学', '模', '跟', '汉', '值', '暴']

In [26]:
char_to_idx = dict([(char, i) for i, char in enumerate(idx_to_char)])

In [29]:
print(char_to_idx)

{'丘': 0, '拥': 1, '唱': 2, '更': 3, '学': 4, '模': 5, '跟': 6, '汉': 7, '值': 8, '暴': 9, '乘': 10, '准': 11, '倦': 12, '阳': 13, '用': 14, '动': 15, '否': 16, '客': 17, '道': 18, '胖': 19, '绪': 20, '言': 21, '熟': 22, '夫': 23, '的': 24, '融': 25, '烟': 26, '脸': 27, 'C': 28, '喝': 29, '仙': 30, '凝': 31, '棒': 32, '桑': 33, '家': 34, '侬': 35, '里': 36, '景': 37, '及': 38, '跳': 39, '再': 40, '瞎': 41, '无': 42, '陪': 43, '人': 44, '还': 45, '白': 46, '解': 47, '爸': 48, '把': 49, '甘': 50, '吐': 51, '许': 52, '细': 53, '相': 54, '做': 55, '专': 56, '间': 57, '降': 58, '婆': 59, '外': 60, '忠': 61, '稀': 62, '杵': 63, '堡': 64, '便': 65, '遇': 66, '拜': 67, '距': 68, '因': 69, '琴': 70, '戏': 71, '蝪': 72, '临': 73, '车': 74, '而': 75, '湖': 76, '形': 77, '渡': 78, '败': 79, '碰': 80, '伤': 81, '声': 82, '符': 83, '春': 84, '翰': 85, '点': 86, '屈': 87, '好': 88, '升': 89, '步': 90, '掩': 91, '选': 92, '奈': 93, '转': 94, '歉': 95, '索': 96, '膀': 97, '呢': 98, '砖': 99, '蟑': 100, '裂': 101, '翅': 102, 'a': 103, '亏': 104, '摩': 105, '么': 106, '晶': 107, '抄': 108, '语': 109, '瓜': 110,

In [30]:
vocab_size = len(char_to_idx)

In [31]:
vocab_size

1027

In [32]:
lyrics_index = [char_to_idx[ch] for ch in lyrics]

In [38]:
sample = lyrics_index[:10]

In [39]:
print("chars: ", ''.join(idx_to_char[idx] for idx in sample))
print("index: ", sample)

chars:  想要有直升机 想要和
index:  [391, 248, 304, 608, 89, 501, 470, 391, 248, 635]
